//
// Generated file, do not edit! Created by nedtool 5.6 from inet/common/chaos/ChaosEvent.msg.
//

#ifndef __INET_CHAOSEVENT_M_H
#define __INET_CHAOSEVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ChaosEvent;
} // namespace inet


namespace inet {

/**
 * Class generated from <tt>inet/common/chaos/ChaosEvent.msg:21</tt> by nedtool.
 * <pre>
 * message ChaosEvent
 * {
 *     int command;
 *     int nodeNum;
 * }
 * </pre>
 */
class INET_API ChaosEvent : public ::omnetpp::cMessage
{
  protected:
    int command = 0;
    int nodeNum = 0;

  private:
    void copy(const ChaosEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ChaosEvent&);

  public:
    ChaosEvent(const char *name=nullptr, short kind=0);
    ChaosEvent(const ChaosEvent& other);
    virtual ~ChaosEvent();
    ChaosEvent& operator=(const ChaosEvent& other);
    virtual ChaosEvent *dup() const override {return new ChaosEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getCommand() const;
    virtual void setCommand(int command);
    virtual int getNodeNum() const;
    virtual void setNodeNum(int nodeNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ChaosEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ChaosEvent& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_CHAOSEVENT_M_H

